// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('search_iphone', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('search_iphone', async function() {
    await driver.get("https://www.amazon.co.uk/")
    await driver.manage().window().setRect(1331, 693)
    await driver.findElement(By.id("twotabsearchtextbox")).click()
    {
      const element = await driver.findElement(By.css(".nav-search-submit > .nav-input"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id("twotabsearchtextbox")).sendKeys("iphone")
    await driver.findElement(By.css(".nav-search-submit > .nav-input")).click()
    await driver.findElement(By.linkText("Best Sellers")).click()
    {
      const element = await driver.findElement(By.linkText("Best Sellers"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id("zg_left_col1")).click()
    assert(await driver.getTitle() == "Amazon.co.uk Best Sellers: The most popular items on Amazon")
    {
      const element = await driver.findElement(By.id("nav-link-prime"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.linkText("New Releases")).click()
    await driver.findElement(By.id("nav-cart")).click()
  })
})
